branches:
  except:
    - /travis/
skip_tags: true

cache:
  - C:\strawberry

install:
  - if not exist "C:\strawberry" choco install strawberryperl --version 5.24.1.1
  - set ST=C:\strawberry
  - set PATH=%ST%\perl\bin;%ST%\perl\site\bin;%ST%\c\bin;%PATH%
  - mkdir %APPVEYOR_BUILD_FOLDER%\tmp
  - set TMPDIR=%APPVEYOR_BUILD_FOLDER%\tmp
  - perl -V
  #- cpan App::cpanminus
  - cpanm -q --notest --showdeps --with-develop --with-suggests . | findstr /v "^perl\>" | cpanm -n
  #- 'echo End install at: & time /t'


build_script:
  - perl Makefile.PL

test_script:
  - dmake test
